### ISSUE TITLE
TripSearch with filtering

### ISSUE THREAD

**Issue by acsant** [CoPilotUW/Orion#6]
Drivers must be able to filter out rider trip requests that do not match their criteria. Vice versa for riders.

**Comment by acsant** [comment]
Adding @Celsius273 to this ticket. I need a list of filter parameters that the front-end will have.

**Comment by Celsius273** [comment]
Filters:

1) Pickup address string (like "Toronto" or "Waterloo") --> param name: "source"
2) Destination address string (same thing as above) --> param name: "destination"

^for flexibility, if we have a trip with pickup "DC Library, Waterloo", a filter with the param value "Waterloo" for pickup will still match this trip.

3) Date: this should match exactly. I'll let you know about the date format later. --> param name: "date"
4) Pickup time: since I don't have an interval for this in the frontend, return any trips that occur after this time (from earliest pickup time to latest pickup time within a reasonable time range, like 3 hours for now) --> param name: "time"
